nginx:
  image: kucing/nginx
  volumes:
    - ./docker/nginx.conf:/etc/nginx/sites-available/default
    - .:/var/www/html
  links:
    - phpfpm
  ports:
    - "8084:80"

phpfpm:
  image: kucing/php56
  volumes:
    - .:/var/www/html
  expose:
    - "9000"
  links:
    - mongodb
    - cmredis
  extra_hosts:
    - "api.elevenia.co.id:112.215.119.91"

phpjobs:
  image: kucing/php56
  command: php artisan queue:listen --sleep=3 --tries=3
  volumes:
    - .:/var/www/html
  working_dir: /var/www/html
  links:
    - mongodb
    - cmredis
  extra_hosts:
      - "api.elevenia.co.id:112.215.119.91"

logdisp:
  image: ubuntu:latest
  command: tail -f /var/www/html/storage/logs/laravel.log
  volumes:
      - .:/var/www/html

mongodb:
  image: mongo
  volumes:
    - ./storage/mongodb:/data/db
  ports:
    - "27018:27017"

cmredis:
  image: redis
